const ALGO = "AES-GCM";
const KEY_BYTES = 32;
const IV_BYTES = 12;

export async function importMasterKey(base64: string): Promise<CryptoKey> {
  const raw = Uint8Array.from(atob(base64), (ch) => ch.charCodeAt(0));
  if (raw.byteLength !== KEY_BYTES) {
    throw new Error(`master key must be ${KEY_BYTES} bytes`);
  }
  return crypto.subtle.importKey("raw", raw, ALGO, false, [
    "encrypt",
    "decrypt",
  ]);
}

// --- Master key quality (GH #223) --------------------------------------------
//
// Length was the only thing ever checked, so the key `docker-compose.dev.yml`
// ships — `dev-master-key-dev-master-key-01`, 32 printable characters, base64
// `ZGV2...MDE=` — is a perfectly valid 32-byte AES key. Copy-pasted into a
// production environment it validates without a word and then decrypts every
// stored mailbox credential and the SSO client secret.
//
// These predicates say only whether a key LOOKS generated; deciding what to do
// about it belongs to core/config.ts, which is the module that knows which
// environment this is. They are heuristics on 32 bytes, so each one is chosen
// to be effectively impossible to trip by chance: the probability that
// `crypto.getRandomValues(new Uint8Array(32))` fails any of them is far below
// the probability of the process being hit by cosmic rays mid-boot.

/**
 * Keys published in this repository. The dev compose key is the one an
 * operator can realistically copy, but any key that ever appears in a file
 * under version control belongs here — being public is what makes it weak,
 * independently of how random it looked when it was generated.
 */
const PUBLISHED_KEYS = new Map<string, string>([
  ["ZGV2LW1hc3Rlci1rZXktZGV2LW1hc3Rlci1rZXktMDE=", "docker-compose.dev.yml"],
]);

/**
 * Minimum distinct byte values expected in a generated 32-byte key. Uniform
 * random bytes average ~30.1 distinct values and essentially never fall below
 * 20, while every hand-written key (a repeated word, a padded phrase, all
 * zeros) sits far under this.
 */
const MIN_DISTINCT_BYTES = 16;

function decodeKey(base64: string): Uint8Array | null {
  try {
    return Uint8Array.from(atob(base64), (ch) => ch.charCodeAt(0));
  } catch {
    // Not base64 at all. importMasterKey is the one that reports that, with a
    // message about the key's shape rather than its quality.
    return null;
  }
}

/**
 * Reports why a base64 master key looks hand-written rather than generated, or
 * `null` when it shows no such sign. The string is a sentence fragment meant to
 * be embedded in a configuration error.
 *
 * A `null` here is NOT a certificate that the key is strong — no local check
 * can be — it only means none of the cheap, decisive tells are present.
 */
export function masterKeyWeakness(base64: string): string | null {
  const published = PUBLISHED_KEYS.get(base64.trim());
  if (published) {
    return `it is the example key published in ${published}, so it is public`;
  }

  const raw = decodeKey(base64);
  if (!raw || raw.byteLength !== KEY_BYTES) return null;

  const distinct = new Set(raw).size;
  if (distinct === 1) {
    return `every one of its ${KEY_BYTES} bytes is identical`;
  }
  if (distinct < MIN_DISTINCT_BYTES) {
    return `it has only ${distinct} distinct byte values out of ${KEY_BYTES}, far below what generated bytes produce`;
  }
  // 0x20-0x7e. A key that is entirely typeable is a passphrase someone wrote,
  // not 32 bytes someone generated: for uniform random bytes the odds are
  // (95/256)^32, about 1 in 10^14.
  if (raw.every((byte) => byte >= 0x20 && byte <= 0x7e)) {
    return `it is made entirely of printable ASCII, so it is a typed passphrase rather than ${KEY_BYTES} generated bytes`;
  }
  return null;
}

// --- Additional authenticated data (GH #347) ---------------------------------
//
// AES-GCM authenticated only the ciphertext: whoever could write
// ciphertext/iv/key_version into a row — a Postgres write, not necessarily the
// master key — could move one row's encrypted columns onto another row's
// primary key and have it decrypt cleanly, because nothing tied a ciphertext
// to WHO or WHAT it was sealed for. `additionalData` closes that: it is mixed
// into the GCM authentication tag at encryption time and must be supplied
// byte-for-byte at decryption, so a ciphertext moved to a different context
// fails tag verification instead of silently decrypting under it.
//
// The context is a short ASCII descriptor of the row's owner/purpose —
// `mail:<userId>`, `"sso"`, `"oidc_state"` — encoded with this helper so every
// caller derives the same bytes from the same string.
export function aadFor(context: string): Uint8Array {
  return new TextEncoder().encode(context);
}

export async function encryptSecret(
  key: CryptoKey,
  plaintext: string,
  additionalData?: Uint8Array,
): Promise<{ ciphertext: Uint8Array; iv: Uint8Array }> {
  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));
  const encrypted = await crypto.subtle.encrypt(
    { name: ALGO, iv, ...(additionalData ? { additionalData } : {}) },
    key,
    new TextEncoder().encode(plaintext),
  );
  return { ciphertext: new Uint8Array(encrypted), iv };
}

/**
 * `additionalData`, when given, must match what `encryptSecret` was called
 * with — otherwise GCM tag verification fails and this throws.
 *
 * Rows written before AAD existed (every row in the database as of GH #347)
 * carry no bound context, so an AAD-bound attempt against one fails for a
 * reason indistinguishable from tampering. The migration-safe fix is a single
 * fallback retry with no AAD at all: it only ever rescues a ciphertext that
 * was genuinely sealed without one, because GCM's tag is computed over the
 * AAD actually used at encryption time — a ciphertext sealed WITH a (now
 * mismatched) context still fails both attempts, which is what keeps a
 * swapped-owner row refused rather than accidentally readable. No migration,
 * `key_version` bump or format marker is needed: the two attempts together
 * cover every row this database has ever written or will write.
 */
export async function decryptSecret(
  key: CryptoKey,
  ciphertext: Uint8Array,
  iv: Uint8Array,
  additionalData?: Uint8Array,
): Promise<string> {
  try {
    const plain = await crypto.subtle.decrypt(
      { name: ALGO, iv: iv as BufferSource, ...(additionalData ? { additionalData } : {}) },
      key,
      ciphertext as BufferSource,
    );
    return new TextDecoder().decode(new Uint8Array(plain));
  } catch (err) {
    if (!additionalData) throw err;
    // Legacy fallback — see the doc comment above. Its own failure (a genuine
    // AAD mismatch, or real tampering) propagates untouched.
    const plain = await crypto.subtle.decrypt(
      { name: ALGO, iv: iv as BufferSource },
      key,
      ciphertext as BufferSource,
    );
    return new TextDecoder().decode(new Uint8Array(plain));
  }
}

// --- Key rotation -----------------------------------------------------------
//
// Every encrypted row stores the `key_version` it was sealed with. A keyring
// holds the current key — the only one that ever encrypts — plus the retired
// keys still needed to read rows that have not been re-encrypted yet. Rotating
// the master key is therefore: promote a new key to current, keep the old one
// listed as retired, and let reads migrate rows progressively.

/** Version stamped by deployments that never rotated: one key, all rows at 1. */
export const DEFAULT_KEY_VERSION = 1;

export type Keyring = {
  /** The only key that encrypts; its version is stamped on every new row. */
  readonly current: { readonly version: number; readonly key: CryptoKey };
  /** Retired keys, indexed by the `key_version` their rows still carry. */
  readonly previous: ReadonlyMap<number, CryptoKey>;
};

export type SealedSecret = {
  ciphertext: Uint8Array;
  iv: Uint8Array;
  keyVersion: number;
};

/**
 * Thrown when a row carries a `key_version` the keyring has no key for. Naming
 * the version is the whole point: it tells the operator which retired key is
 * missing from the configuration.
 */
export class UnknownKeyVersionError extends Error {
  readonly version: number;

  constructor(version: number, known: number[]) {
    super(
      `no master key for key_version ${version}; keyring holds ${known.join(", ")}`,
    );
    this.name = "UnknownKeyVersionError";
    this.version = version;
  }
}

function assertValidVersion(version: number): void {
  if (!Number.isInteger(version) || version < 1) {
    throw new Error(`key version must be a positive integer, got ${version}`);
  }
}

export function createKeyring(
  current: { version: number; key: CryptoKey },
  previous: ReadonlyMap<number, CryptoKey> = new Map(),
): Keyring {
  assertValidVersion(current.version);
  for (const version of previous.keys()) {
    assertValidVersion(version);
    if (version === current.version) {
      throw new Error(
        `key version ${version} is both current and retired; a version identifies exactly one key`,
      );
    }
  }
  return { current, previous: new Map(previous) };
}

/**
 * Accepts either a keyring or a bare key. A bare key is the pre-rotation
 * deployment that only ever set `MASTER_KEY`: one key, every row at version 1.
 */
export function asKeyring(keys: CryptoKey | Keyring): Keyring {
  if ("current" in keys && "previous" in keys) return keys;
  return createKeyring({ version: DEFAULT_KEY_VERSION, key: keys });
}

export function knownKeyVersions(keyring: Keyring): number[] {
  return [keyring.current.version, ...keyring.previous.keys()].sort((a, b) => a - b);
}

export function keyForVersion(keyring: Keyring, version: number): CryptoKey | null {
  if (version === keyring.current.version) return keyring.current.key;
  return keyring.previous.get(version) ?? null;
}

export async function encryptWithKeyring(
  keyring: Keyring,
  plaintext: string,
  additionalData?: Uint8Array,
): Promise<SealedSecret> {
  const { ciphertext, iv } = await encryptSecret(keyring.current.key, plaintext, additionalData);
  return { ciphertext, iv, keyVersion: keyring.current.version };
}

export async function decryptWithKeyring(
  keyring: Keyring,
  secret: SealedSecret,
  additionalData?: Uint8Array,
): Promise<string> {
  const key = keyForVersion(keyring, secret.keyVersion);
  if (!key) {
    throw new UnknownKeyVersionError(secret.keyVersion, knownKeyVersions(keyring));
  }
  return decryptSecret(key, secret.ciphertext, secret.iv, additionalData);
}
