import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import "../../app/i18n";
import i18n from "../../app/i18n";
import type { SieveRawScript } from "@webmail/shared";
import { MailApiError } from "../mailbox/api";
import { SieveAdvancedEditor } from "./SieveAdvanced";

const {
  fetchSieveRawScript,
  fetchGeneratedSieveScript,
  saveSieveRawScript,
  switchToRuleBuilder,
} = vi.hoisted(() => ({
  fetchSieveRawScript: vi.fn(),
  fetchGeneratedSieveScript: vi.fn(),
  saveSieveRawScript: vi.fn(),
  switchToRuleBuilder: vi.fn(),
}));

vi.mock("./api", async (importOriginal) => {
  const actual = await importOriginal<typeof import("./api")>();
  return {
    ...actual,
    fetchSieveRawScript,
    fetchGeneratedSieveScript,
    saveSieveRawScript,
    switchToRuleBuilder,
  };
});

const GENERATED = '# Generated by webmail. Do not edit manually.\n\n# rule: invoices\n';
const HAND_WRITTEN = 'require ["fileinto"];\nfileinto "Ops";\n';

const RULES_MODE: SieveRawScript = { mode: "rules", script: "", updatedAt: null };
const RAW_MODE: SieveRawScript = {
  mode: "raw",
  script: HAND_WRITTEN,
  updatedAt: "2026-07-01T10:00:00.000Z",
};

/** Renders with whatever the state fetcher is already stubbed to do. */
function renderRaw() {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <QueryClientProvider client={client}>
      <SieveAdvancedEditor />
    </QueryClientProvider>,
  );
}

function renderEditor(state: SieveRawScript = RULES_MODE) {
  fetchSieveRawScript.mockResolvedValue(state);
  renderRaw();
}

/** Opens the disclosure and waits for the textarea to be there. */
async function open() {
  fireEvent.click(screen.getByRole("button", { name: i18n.t("filters.advanced.title") }));
  return screen.findByLabelText(i18n.t("filters.advanced.label"));
}

// GH #23: the raw Sieve editor for the rules the structured builder does not
// cover. Everything worth asserting here is about the handover between the two
// authors of one script — above all that no path through it loses the script
// the user wrote by hand.
describe("SieveAdvancedEditor", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    fetchGeneratedSieveScript.mockResolvedValue({ script: GENERATED });
  });

  it("costs nothing until a power user opens it", async () => {
    renderEditor();

    await waitFor(() => expect(fetchSieveRawScript).toHaveBeenCalled());
    expect(screen.queryByLabelText(i18n.t("filters.advanced.label"))).not.toBeInTheDocument();
    // The generated preview is a JMAP round-trip on the server: an account that
    // never opens the editor must not pay for it.
    expect(fetchGeneratedSieveScript).not.toHaveBeenCalled();
  });

  it("seeds the editor with the script the rules produce", async () => {
    renderEditor();

    expect(await open()).toHaveValue(GENERATED);
    expect(screen.getByText(i18n.t("filters.advanced.intro"))).toBeInTheDocument();
  });

  it("says plainly what saving will do before it is saved", async () => {
    renderEditor();
    await open();

    // The consequence has to be stated where the decision is made — explaining
    // it after the click is not a choice the user got to make.
    expect(screen.getByText(i18n.t("filters.advanced.takeoverWarning"))).toBeInTheDocument();
    // Nothing to go "back" to yet: the rule builder already owns the script.
    expect(
      screen.queryByRole("button", { name: i18n.t("filters.advanced.useRules") }),
    ).not.toBeInTheDocument();
  });

  it("takes the script over with the edited text", async () => {
    saveSieveRawScript.mockResolvedValueOnce(RAW_MODE);
    renderEditor();

    const textarea = await open();
    fireEvent.change(textarea, { target: { value: HAND_WRITTEN } });
    fireEvent.click(screen.getByRole("button", { name: i18n.t("filters.advanced.save") }));

    await waitFor(() => expect(saveSieveRawScript).toHaveBeenCalledWith(HAND_WRITTEN));
    expect(await screen.findByText(i18n.t("filters.advanced.saved"))).toBeInTheDocument();
  });

  it("shows the stored script, not a regenerated one, once it owns the account", async () => {
    renderEditor(RAW_MODE);

    expect(await open()).toHaveValue(HAND_WRITTEN);
    expect(screen.getByText(i18n.t("filters.advanced.active"))).toBeInTheDocument();
    // A user with a script wants THAT script back — asking the server to
    // regenerate one over it is both wasted work and the wrong answer.
    expect(fetchGeneratedSieveScript).not.toHaveBeenCalled();
  });

  it("offers the way back, and says the script survives it", async () => {
    switchToRuleBuilder.mockResolvedValueOnce({ ...RAW_MODE, mode: "rules" });
    renderEditor(RAW_MODE);
    await open();

    expect(screen.getByText(i18n.t("filters.advanced.keptOnReturn"))).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: i18n.t("filters.advanced.useRules") }));

    await waitFor(() => expect(switchToRuleBuilder).toHaveBeenCalledTimes(1));
    // Still in the editor, unchanged: going back deactivates the script, it
    // does not take it away, and the user can save it again to re-activate it.
    expect(screen.getByLabelText(i18n.t("filters.advanced.label"))).toHaveValue(HAND_WRITTEN);
  });

  it("keeps the rejected script on screen when the mail server refuses it", async () => {
    saveSieveRawScript.mockRejectedValueOnce(new MailApiError(422, "sieve_invalid"));
    renderEditor(RAW_MODE);

    const textarea = await open();
    fireEvent.change(textarea, { target: { value: "if header {" } });
    fireEvent.click(screen.getByRole("button", { name: i18n.t("filters.advanced.save") }));

    const alert = await screen.findByRole("alert");
    // Not the shared sieve_invalid message: that one is about the GENERATED
    // script and tells the user to call an administrator, which is the wrong
    // advice for a script they just typed.
    expect(alert).toHaveTextContent(i18n.t("filters.advanced.rejected"));
    // The broken script is exactly where they left it — losing it to a failed
    // save would be its own way of discarding a user's work.
    expect(screen.getByLabelText(i18n.t("filters.advanced.label"))).toHaveValue("if header {");
  });

  it("reports an ordinary save failure through the shared message map", async () => {
    saveSieveRawScript.mockRejectedValueOnce(new MailApiError(502, "sieve_sync_failed"));
    renderEditor(RAW_MODE);
    await open();
    fireEvent.click(screen.getByRole("button", { name: i18n.t("filters.advanced.save") }));

    expect(await screen.findByRole("alert")).toHaveTextContent(
      i18n.t("settings.errors.sieve_sync_failed"),
    );
  });

  it("reports a failed hand-back rather than pretending it worked", async () => {
    switchToRuleBuilder.mockRejectedValueOnce(new MailApiError(502, "sieve_sync_failed"));
    renderEditor(RAW_MODE);
    await open();
    fireEvent.click(screen.getByRole("button", { name: i18n.t("filters.advanced.useRules") }));

    expect(await screen.findByRole("alert")).toHaveTextContent(
      i18n.t("settings.errors.sieve_sync_failed"),
    );
  });

  it("offers a retry instead of an empty editor when the state cannot be read", async () => {
    fetchSieveRawScript.mockRejectedValue(new MailApiError(503, "database_unavailable"));
    renderRaw();
    fireEvent.click(screen.getByRole("button", { name: i18n.t("filters.advanced.title") }));

    expect(await screen.findByRole("alert")).toHaveTextContent(i18n.t("settings.errors.generic"));
    // An editor seeded with nothing would invite the user to save an empty
    // script over whatever is really stored.
    expect(screen.queryByLabelText(i18n.t("filters.advanced.label"))).not.toBeInTheDocument();
  });

  it("offers a retry when the seed itself cannot be read", async () => {
    fetchGeneratedSieveScript.mockRejectedValue(new MailApiError(502, "stalwart_unavailable"));
    renderEditor();
    fireEvent.click(screen.getByRole("button", { name: i18n.t("filters.advanced.title") }));

    expect(await screen.findByRole("alert")).toBeInTheDocument();
    expect(screen.queryByLabelText(i18n.t("filters.advanced.label"))).not.toBeInTheDocument();

    fetchGeneratedSieveScript.mockResolvedValue({ script: GENERATED });
    fireEvent.click(screen.getByRole("button", { name: i18n.t("settings.retry") }));

    expect(await screen.findByLabelText(i18n.t("filters.advanced.label"))).toHaveValue(GENERATED);
  });

  it("shows the loading state, never an empty editor, before the seed arrives", async () => {
    fetchGeneratedSieveScript.mockReturnValue(new Promise(() => {}));
    renderEditor();
    fireEvent.click(screen.getByRole("button", { name: i18n.t("filters.advanced.title") }));

    expect(await screen.findByTestId("settings-loading")).toBeInTheDocument();
    expect(screen.queryByLabelText(i18n.t("filters.advanced.label"))).not.toBeInTheDocument();
  });

  it("closes again without losing what was typed", async () => {
    renderEditor(RAW_MODE);
    const textarea = await open();
    fireEvent.change(textarea, { target: { value: "# work in progress\n" } });

    fireEvent.click(screen.getByRole("button", { name: i18n.t("filters.advanced.title") }));
    expect(screen.queryByLabelText(i18n.t("filters.advanced.label"))).not.toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: i18n.t("filters.advanced.title") }));
    expect(await screen.findByLabelText(i18n.t("filters.advanced.label"))).toHaveValue(
      "# work in progress\n",
    );
  });
});
