import type {
  FilterAction,
  FilterCondition,
  FilterRule,
  VacationSettings,
} from "@webmail/shared";

export type SieveGeneratorInput = {
  rules: FilterRule[];
  vacation: VacationSettings | null;
  trashFolder: string;
};

function sanitizeSingleLine(value: string): string {
  return value.replace(/[\u0000-\u001f\u007f]/g, " ");
}

function quote(value: string): string {
  return `"${sanitizeSingleLine(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function textBlock(value: string): string {
  const lines = value
    .replace(/\r\n?/g, "\n")
    .replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g, " ")
    .split("\n")
    .map((line) => (line.startsWith(".") ? `.${line}` : line));
  return `text:\r\n${lines.join("\r\n")}\r\n.\r\n`;
}

function conditionToSieve(condition: FilterCondition, requires: Set<string>): string {
  const match = condition.op === "is" ? ":is" : ":contains";
  const value = quote(condition.value);
  switch (condition.field) {
    case "from":
      return `header ${match} "from" ${value}`;
    case "to":
      return `header ${match} ["to", "cc"] ${value}`;
    case "subject":
      return `header ${match} "subject" ${value}`;
    case "body":
      requires.add("body");
      return `body :text ${match} ${value}`;
  }
}

function actionToSieve(
  action: FilterAction,
  trashFolder: string,
  requires: Set<string>,
): string {
  switch (action.type) {
    case "fileinto":
      requires.add("fileinto");
      return `fileinto ${quote(action.folder)};`;
    case "seen":
      requires.add("imap4flags");
      return `addflag "\\\\Seen";`;
    case "flag":
      requires.add("imap4flags");
      return `addflag ${quote(action.keyword)};`;
    case "delete":
      requires.add("fileinto");
      return `fileinto ${quote(trashFolder)};`;
    case "stop":
      return "stop;";
  }
}

function ruleToSieve(rule: FilterRule, trashFolder: string, requires: Set<string>): string {
  const tests = rule.conditions.map((condition) => conditionToSieve(condition, requires));
  const combinator = rule.matchType === "any" ? "anyof" : "allof";
  const test = tests.length === 1 ? tests[0]! : `${combinator} (${tests.join(", ")})`;
  const actions = rule.actions
    .map((action) => `  ${actionToSieve(action, trashFolder, requires)}`)
    .join("\n");
  // safe without quote(): sanitized single line inside a #-to-end-of-line comment
  return `# rule: ${sanitizeSingleLine(rule.name)}\nif ${test} {\n${actions}\n}`;
}

function vacationToSieve(vacation: VacationSettings, requires: Set<string>): string {
  requires.add("vacation");
  const args = [`:days ${vacation.intervalDays}`];
  if (vacation.subject !== "") {
    args.push(`:subject ${quote(vacation.subject)}`);
  }
  const command = `vacation ${args.join(" ")} ${textBlock(vacation.message)};`;
  const dateTests: string[] = [];
  if (vacation.startsAt) {
    dateTests.push(`currentdate :value "ge" "date" ${quote(vacation.startsAt)}`);
  }
  if (vacation.endsAt) {
    dateTests.push(`currentdate :value "le" "date" ${quote(vacation.endsAt)}`);
  }
  if (dateTests.length === 0) {
    return command;
  }
  requires.add("date");
  requires.add("relational");
  const test = dateTests.length === 1 ? dateTests[0]! : `allof (${dateTests.join(", ")})`;
  return `if ${test} {\n  ${command}\n}`;
}

export function generateSieveScript(input: SieveGeneratorInput): string {
  const requires = new Set<string>();
  const parts: string[] = [];
  const rules = [...input.rules].sort((a, b) => a.position - b.position);
  for (const rule of rules) {
    if (!rule.enabled || rule.conditions.length === 0 || rule.actions.length === 0) {
      continue;
    }
    parts.push(ruleToSieve(rule, input.trashFolder, requires));
  }
  const vacation = input.vacation;
  if (vacation && vacation.enabled && vacation.message.trim() !== "") {
    parts.push(vacationToSieve(vacation, requires));
  }
  if (parts.length === 0) {
    return "";
  }
  const header = "# Generated by webmail. Do not edit manually.";
  const requireLine = `require [${[...requires]
    .sort()
    .map((name) => `"${name}"`)
    .join(", ")}];`;
  const sections = requires.size > 0 ? [header, requireLine, ...parts] : [header, ...parts];
  return `${sections.join("\n\n")}\n`;
}
